# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('exchange', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
