# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='current_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='currency',
            name='previous_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
    ]
