# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finsite', '0002_auto_20170427_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyHistoryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('time', models.DateField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finsite.Currency')),
            ],
        ),
    ]
