# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finsite', '0004_auto_20170503_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyhistoryrecord',
            name='volume',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
