# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 09:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finsite', '0008_newsitem_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordSynonims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('synonyms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
        ),
    ]
