# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finsite', '0011_newsitem_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='language',
            field=models.CharField(default='ru', max_length=4),
        ),
    ]
