# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 11:28
from __future__ import unicode_literals

from django.db import migrations, models
from finsite.models.exchange import Exchange
import django.db.models.deletion


def create_exchanges(*args):
    Exchange.objects.create(name='Kraken', pseudonym='Kraken')
    Exchange.objects.create(name='Poloniex', pseudonym='Poloniex')

class Migration(migrations.Migration):

    dependencies = [
        ('finsite', '0014_auto_20170729_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pseudonym', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(create_exchanges),
        migrations.RemoveField(
            model_name='currency',
            name='description',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='summary',
        ),
        migrations.AddField(
            model_name='currency',
            name='prediction_status',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=0),
        ),
        migrations.AlterField(
            model_name='currency',
            name='ordering',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='currencyhistoryrecord',
            name='exchange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finsite.Exchange'),
        ),
        migrations.AddField(
            model_name='currency',
            name='exchange_list',
            field=models.ManyToManyField(related_name='exchange_list', to='finsite.Exchange'),
        ),
        migrations.AddField(
            model_name='currency',
            name='selected_exchange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finsite.Exchange'),
        ),
    ]
