# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finsite', '0015_auto_20170806_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='link',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
