# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finsite', '0017_currency_url_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTextReplacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_string', models.CharField(max_length=255)),
                ('to_string', models.CharField(max_length=255)),
            ],
        ),
    ]
