# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finsite', '0018_newstextreplacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstextreplacement',
            name='to_string',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
